; If this changes, restart the master container with docker-compose restart master
; Note: inline comments not supported!

[host]
port=$MASTER_SERVER_PORT
name=Bitfighter Master Server
latest_released_cs_protocol=41
latest_released_client_build_version=12342
; /home/master/web-shared is mapped to web container
json_file=/home/master/web-shared/bitfighterStatus.json

[stats]
stats_database_addr=$DATABASE_HOST
stats_database_name=$BF_STATS_DB
stats_database_username=$BF_STATS_USER
stats_database_password=$BF_STATS_PASSWORD
write_stats_to_mysql=Yes
;sqlite_file_basename=stats

[phpbb]
phpbb3_database_name=$PHPBB_DB
phpbb3_database_address=$DATABASE_HOST
phpbb3_table_prefix=$PHPBB3_TABLE_PREFIX
phpbb3_database_username=$PHPBB_USER
phpbb3_database_password=$PHPBB_PASSWORD

[motd_clients]
1836=Time to upgrade!  New version available at bitfighter.org

[motd]
motd_file=/home/master/bitfighter/exe/motd

[GameJolt]
UseGameJolt=Yes
GameJoltSecret=$GAME_JOLT_SECRET

[system]
; Currently curl is only used for GameJolt integration
path_to_curl=/usr/bin/curl