Document: bitfighter
Title: Debian bitfighter Manual
Author: <insert document author here>
Abstract: This manual describes what bitfighter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bitfighter/bitfighter.sgml.gz

Format: postscript
Files: /usr/share/doc/bitfighter/bitfighter.ps.gz

Format: text
Files: /usr/share/doc/bitfighter/bitfighter.text.gz

Format: HTML
Index: /usr/share/doc/bitfighter/html/index.html
Files: /usr/share/doc/bitfighter/html/*.html
