name: Build Packages
on:
  push:
    branches:
      - master
    tags:
  release:
  pull_request:
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y cmake libphysfs-dev libsdl2-dev libopenal-dev libvorbis-dev libmodplug-dev libspeex-dev
      - run: cd build && cmake .. && make
      - run: cp -R resource/* exe/
      - uses: actions/upload-artifact@v3
        with:
          name: Bitfighter-Linux
          path: |
            exe/
